-- 코드를 입력하세요

SELECT 
ATR.AUTHOR_ID
, ATR.AUTHOR_NAME
, BK.CATEGORY
, SUM(SUM_TBL.BK_SUM * bk.price) AS TOTAL_SALES
FROM book bk
INNER JOIN author atr 
ON bk.author_id = atr.author_id
INNER JOIN (
SELECT
BOOK_ID
, SUM(SALES) AS BK_SUM
FROM BOOK_SALES
WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202201'
group by book_id
) SUM_TBL 
ON SUM_TBL.BOOK_ID = BK.BOOK_ID
group by AUTHOR_ID, CATEGORY
ORDER BY ATR.AUTHOR_ID, BK.CATEGORY DESC




/*
SELECT
BOOK_ID
, SUM(SALES)
FROM BOOK_SALES
WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202201'
group by book_id
*/