-- 코드를 입력하세요
# SELECT
# *
# FROM CAR_RENTAL_COMPANY_CAR 


SELECT 
 DISTINCT CAR_ID
 , CRCC.CAR_TYPE
 , TRUNCATE((CRCC.DAILY_FEE - (CRCC.DAILY_FEE * (CRCDP.DISCOUNT_RATE/100) )) * 30, 0) AS FEE
FROM
CAR_RENTAL_COMPANY_CAR CRCC
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
        ON CRCDP.CAR_TYPE = CRCC.CAR_TYPE
WHERE CRCC.CAR_TYPE IN ('세단', 'SUV')
    AND CRCDP.DURATION_TYPE = '30일 이상'
    AND TRUNCATE((CRCC.DAILY_FEE - (CRCC.DAILY_FEE * (CRCDP.DISCOUNT_RATE/100) )) * 30, 0) BETWEEN 500000 AND 2000000
    AND NOT EXISTS(
        SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
            WHERE CRCRH.CAR_ID = CRCC.CAR_ID
                AND (CRCRH.START_DATE <= '2022-11-30' AND CRCRH.END_DATE >= '2022-11-01')
)
    ORDER BY 
        FEE DESC
        , CRCC.CAR_TYPE
        , CRCC.CAR_ID DESC
        
    
        
# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE ('2022-11-01' > END_DATE OR '2022-11-30' < START_DATE)

# END DATE 가 시작일 보다 작거나 종료일이 start date 보다 크다

        
        
        