-- 코드를 입력하세요

SELECT 
    AO.ANIMAL_ID
    , AO.ANIMAL_TYPE
    , AO.NAME
FROM ANIMAL_OUTS AO
INNER JOIN (
        SELECT
            ANIMAL_ID
            , SEX_UPON_INTAKE
        FROM ANIMAL_INS
        WHERE SEX_UPON_INTAKE NOT IN ('Spayed Female', 'Neutered Male')
    ) TBL ON TBL.ANIMAL_ID = AO.ANIMAL_ID
    
WHERE AO.SEX_UPON_OUTCOME != TBL.SEX_UPON_INTAKE
ORDER BY AO.ANIMAL_ID