-- 코드를 입력하세요

SELECT 
YEAR
, MONTH
, GENDER
, COUNT(USER_ID) AS USERS
FROM (
SELECT
DISTINCT UI.USER_ID  
, YEAR(SALES_DATE) AS YEAR
, MONTH(SALES_DATE) AS MONTH
, UI.GENDER
FROM ONLINE_SALE OS
    INNER JOIN USER_INFO UI
        ON UI.USER_ID = OS.USER_ID  
WHERE UI.GENDER IS NOT NULL
) RES_TBL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
