-- 코드를 작성해주세요

SELECT 
    COUNT(CASE WHEN LENGTH IS NOT NULL THEN 1 ELSE 0 END) AS FISH_COUNT
    , FISH_NAME
FROM FISH_INFO FI
    INNER JOIN FISH_NAME_INFO FNI
        ON FNI.FISH_TYPE = FI.FISH_TYPE
GROUP BY FI.FISH_TYPE, FISH_NAME
ORDER BY FISH_COUNT DESC