-- 코드를 입력하세요


SELECT
FP.PRODUCT_ID
, FP.PRODUCT_NAME
, SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
    INNER JOIN (
        SELECT PRODUCT_ID, AMOUNT FROM FOOD_ORDER 
        WHERE DATE_FORMAT(PRODUCE_DATE, '%Y%m') = '202205'
    ) FO ON FO.PRODUCT_ID = FP.PRODUCT_ID
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

