-- 코드를 입력하세요

with RECURSIVE HOUR_TBL as (
    SELECT
    0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 AS H 
    FROM HOUR_TBL
    WHERE HOUR < 23
)
SELECT
HT.HOUR
, CASE WHEN AO_TBL.COUNT IS NULL THEN 0 ELSE AO_TBL.COUNT END  AS COUNT
FROM HOUR_TBL HT
LEFT JOIN
(SELECT
HOUR(DATETIME) AS HOUR
, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR) AO_TBL
ON AO_TBL.HOUR = HT.HOUR