-- 코드를 작성해주세요

SELECT
HE.EMP_NO
, HE.EMP_NAME
, CASE WHEN AVG(HG.SCORE) >= 96 THEN 'S'
    WHEN AVG(HG.SCORE) >= 90 THEN 'A'
    WHEN AVG(HG.SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END AS GRADE
, CASE WHEN AVG(HG.SCORE) >= 96 THEN (MAX(HE.SAL) * 0.2)
    WHEN AVG(HG.SCORE) >= 90 THEN (MAX(HE.SAL) * 0.15)
    WHEN AVG(HG.SCORE) >= 80 THEN (MAX(HE.SAL) * 0.1)
    ELSE (MAX(HE.SAL) * 0)
    END AS BONUS
FROM HR_DEPARTMENT HD
    INNER JOIN HR_EMPLOYEES HE 
        ON HE.DEPT_ID = HD.DEPT_ID
    INNER JOIN HR_GRADE HG
        ON HG.EMP_NO = HE.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO