-- 코드를 입력하세요
# SELECT
# *
# FROM MEMBER_PROFILE

SELECT 
    MP.MEMBER_NAME
    , RR.REVIEW_TEXT
    , DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN (
SELECT * FROM REST_REVIEW 
WHERE MEMBER_ID = (
    SELECT
        MEMBER_ID
    FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)
) RR
ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT

