-- 코드를 입력하세요

SELECT 
MONTH(CRCRH.START_DATE) AS MONTH
, CRCRH.CAR_ID AS CAR_ID
, COUNT(CRCRH.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
INNER JOIN (
SELECT 
CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
START_DATE BETWEEN '2022-08-01' and '2022-11-01'
group by CAR_ID
having count(CAR_ID) > 4) temp
ON temp.car_id = CRCRH.car_id

WHERE CRCRH.START_DATE BETWEEN '2022-08-01' and '2022-11-01'
GROUP BY MONTH(CRCRH.START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC
