-- 코드를 작성해주세요


SELECT
YEAR(ED.DIFFERENTIATION_DATE) AS YEAR
, (TEMP.SIZE_OF_COLONY - ED.SIZE_OF_COLONY) AS YEAR_DEV
, CAST(ED.ID AS SIGNED) AS ID
FROM ECOLI_DATA ED
LEFT JOIN (
SELECT
MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
) TEMP 
ON TEMP.YEAR = YEAR(ED.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV