-- 코드를 작성해주세요

SELECT
*
FROM (
SELECT 
    CASE 
    WHEN (GROUP_CONCAT(SC.NAME) LIKE '%React%' OR GROUP_CONCAT(SC.NAME) LIKE '%Vue%' OR GROUP_CONCAT(SC.NAME) LIKE '%JavaScript%') AND (GROUP_CONCAT(SC.NAME) LIKE '%Python%') THEN 'A' 
    WHEN GROUP_CONCAT(SC.NAME) LIKE '%C#%' THEN 'B'
    WHEN GROUP_CONCAT(SC.CATEGORY) LIKE '%Front%' THEN 'C'
    END AS GRADE
    , DEV.ID
    , DEV.EMAIL
FROM DEVELOPERS DEV
    INNER JOIN SKILLCODES SC
    ON SC.CODE & DEV.SKILL_CODE = SC.CODE
    GROUP BY DEV.ID, DEV.EMAIL
    ) TBL 
    WHERE TBL.GRADE IS NOT NULL
    ORDER BY GRADE, ID
